# This is set to trigger the workflow on push in below branches but avoid trigger the workflow when the change is in the given path.
name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev-*' # dev-new, dev-new-this
      - 'feat/**' # feat/new, feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # dev-new, dev-new-this
      - 'feat/**' # feat/new, feat/new/button
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
